### PR TITLE
add scripts for generating icann lookup and response code csvs

### PR DESCRIPTION
**Pull request by loganmeetsworld**
# Add lookup/response scripts #

## 🗣 Description ##

I have generated some data for the team and these are scripts for performing ICANN lookups and retrieving response statuses for domains. These are the basic versions without any sort of asynchronous processing of the requests. I run these with tmux for a long period locally. 

## 💭 Motivation and context ##

We have certain research questions about the rate of responses for the current list of domains. We also have questions about current registrar usage. This helps us answer some of those questions with data. 

## Questions for reviewers ##

Should I add the current set of generated data to this repository? This would allow us to show notebooks using the data with research questions.

### CODE REVIEW

**Review by SSPJ — APPROVED** [review]
I have not tested these scripts, but I've read the code and can't see any issues with it.

👍

**Comment by SSPJ** [comment]
> Should I add the current set of generated data to this repository? This would allow us to show notebooks using the data with research questions.

I have some concerns about committing data which will become outdated. Having the data in our drive might be a more accessible format for the UX folks as well.

**Review by h-m-f-t — APPROVED** [review]
* I was able to run response_codes.py successfully and the results are as expected.
* I kept hitting the exception in L24 in icann_lookup.py ("Something went wrong").

It'd be good to have another person do a successful run before merging, but that's not _really_ necessary for little scripts like this, intended for local use.

**Comment by loganmeetsworld** [comment]
> I kept hitting the exception in L24 in icann_lookup.py ("Something went wrong").

@h-m-f-t that's fine as long as the script didn't exit. It should hit that and report something went wrong and keep running.

**Pull request merged**
